config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  resources :exos

  resources :products

end

app/models/exo.rb
class Exo < ActiveRecord::Base

  def self.import(file, trainer_id)
    trainerone = Trainerone.find(trainer_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      trainer = Trainerone.create! row.to_hash
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when '.csv' then Csv.new(file.path, nil, :ignore)
      when '.xls' then Excel.new(file.path, nil, :ignore)
      when '.xlsx' then Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end


end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base























  # # Insert Facilities
  # puts "Importing Facilities..."
  # spreadsheet = Roo::Excelx.new('app/assets/data/facilities.xlsx', nil, :ignore)
  # header = spreadsheet.row(1)
  # (2..spreadsheet.last_row).each do |i|
  #   row = Hash[[header, spreadsheet.row(i)].transpose]
  #   facility = Facility.find_by_id(row['id']) || Facility.new
  #   facility.attributes = row.to_hash.slice(*row.to_hash.keys)
  #   facility.save!
  # end
  # puts "Facilities imported. "


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exos_controller.rb
class ExosController < ApplicationController
  before_action :set_exo, only: [:show, :edit, :update, :destroy]

  def import
    @trainerone = Trainerone.find(params[:trainerone_id])

    Trainerone.import(params[:file], @trainerone.id)
    redirect_to @trainerone, notice: "Import Success."
  end

  # GET /exos
  # GET /exos.json
  def index
    @exos = Exo.order("PrdName").all
  end

  # GET /exos/1
  # GET /exos/1.json
  def show
  end

  # GET /exos/new
  def new
    @exo = Exo.new
  end

  # GET /exos/1/edit
  def edit
  end

  # POST /exos
  # POST /exos.json
  def create
    @exo = Exo.new(exo_params)

    respond_to do |format|
      if @exo.save
        format.html { redirect_to @exo, notice: 'Exo was successfully created.' }
        format.json { render :show, status: :created, location: @exo }
      else
        format.html { render :new }
        format.json { render json: @exo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exos/1
  # PATCH/PUT /exos/1.json
  def update
    respond_to do |format|
      if @exo.update(exo_params)
        format.html { redirect_to @exo, notice: 'Exo was successfully updated.' }
        format.json { render :show, status: :ok, location: @exo }
      else
        format.html { render :edit }
        format.json { render json: @exo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exos/1
  # DELETE /exos/1.json
  def destroy
    @exo.destroy
    respond_to do |format|
      format.html { redirect_to exos_url, notice: 'Exo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exo
      @exo = Exo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exo_params
      params.require(:exo).permit(:PrdName, :OwnerName)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:DateSent, :DatePage, :NumEY, :OrderNo, :AccCode, :PrdName, :OwnerName, :PhoneNo, :MobileNo, :ZipCode, :Address, :iWeight, :Name1, :Cnt1, :iPrice, :Memo, :iPage)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:PrdName, :OwnerName, :PhoneNo, :MobileNo, :ZipCode, :Address, :iWeight, :Name1, :Cnt1, :iPrice, :Memo, :iPage, :OrderNo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exos_helper.rb
module ExosHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/exos/_form.html.erb
<%= form_for(@exo) do |f| %>
  <% if @exo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exo.errors.count, "error") %> prohibited this exo from being saved:</h2>

      <ul>
      <% @exo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PrdName %><br>
    <%= f.text_field :PrdName %>
  </div>
  <div class="field">
    <%= f.label :OwnerName %><br>
    <%= f.text_field :OwnerName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exos/edit.html.erb
<h1>Editing Exo</h1>

<%= render 'form' %>

<%= link_to 'Show', @exo %> |
<%= link_to 'Back', exos_path %>

app/views/exos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exos</h1>

<table>
  <thead>
    <tr>
      <td>No</td>
      <th>Prdname</th>
      <th>Ownername</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exos.each do |exo| %>
      <tr>
        <td><%= exo.id-50 %></td>        <!--  땜빵 -->
        <td><%= exo.PrdName %></td>
        <td><%= exo.OwnerName %></td>
        <td><%= link_to 'Show', exo %></td>
        <td><%= link_to 'Edit', edit_exo_path(exo) %></td>
        <td><%= link_to 'Destroy', exo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exo', new_exo_path %>

app/views/exos/new.html.erb
<h1>New Exo</h1>

<%= render 'form' %>

<%= link_to 'Back', exos_path %>

app/views/exos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prdname:</strong>
  <%= @exo.PrdName %>
</p>

<p>
  <strong>Ownername:</strong>
  <%= @exo.OwnerName %>
</p>

<%= link_to 'Edit', edit_exo_path(@exo) %> |
<%= link_to 'Back', exos_path %>

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DateSent %><br> <%= f.text_field :DateSent %>
  </div>
  <div class="field">
    <%= f.label :DatePage %><br> <%= f.text_field :DatePage %>
  </div>
  <div class="field">
    <%= f.label :NumEY %><br> <%= f.text_field :NumEY %>
  </div>
  <div class="field">
    <%= f.label :OrderNo %><br> <%= f.text_field :OrderNo %>
  </div>
  <div class="field">
    <%= f.label :AccCode %><br> <%= f.text_field :AccCode %>
  </div>
  <div class="field">
    <%= f.label :PrdName %><br> <%= f.text_field :PrdName %>
  </div>
  <div class="field">
    <%= f.label :OwnerName %><br> <%= f.text_field :OwnerName %>
  </div>
  <div class="field">
    <%= f.label :PhoneNo %><br> <%= f.text_field :PhoneNo %>
  </div>
  <div class="field">
    <%= f.label :MobileNo %><br> <%= f.text_field :MobileNo %>
  </div>
  <div class="field">
    <%= f.label :ZipCode %><br> <%= f.text_field :ZipCode %>
  </div>
  <div class="field">
    <%= f.label :Address %><br> <%= f.text_field :Address %>
  </div>
  <div class="field">
    <%= f.label :iWeight %><br> <%= f.number_field :iWeight %>
  </div>
  <div class="field">
    <%= f.label :Name1 %><br> <%= f.text_field :Name1 %>
  </div>
  <div class="field">
    <%= f.label :Cnt1 %><br> <%= f.text_field :Cnt1 %>
  </div>
  <div class="field">
    <%= f.label :iPrice %><br> <%= f.number_field :iPrice %>
  </div>
  <div class="field">
    <%= f.label :Memo %><br> <%= f.text_field :Memo %>
  </div>
  <div class="field">
    <%= f.label :iPage %><br> <%= f.number_field :iPage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<script src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.js"></script>
<script src="https://jquery-barcode.googlecode.com/files/jquery.barcode.0.3.js"></script>
<script>
    $(document).ready(function(){

                $('.barcode39') .barcode({code:'code39'});

                generateI25 = function(){
                    $('.barcodeI25').barcode({code:'I25'});
                };

            }
    );
</script>
<% @invoices.each do |ii| %>
        <div id="page">
          <table width="500" class="header">
            <tr>
              <td>&nbsp;</td>        <td>&nbsp;</td>        <td><%= ii.NumEY %></td>        <td>&nbsp;</td>
            </tr>
            <tr>
              <td width="13">&nbsp;</td>        <td width="170">  <%= ii.PrdName[0..-2]+"**" %></td>        <td width="153"> <%= ii.PhoneNo[0..-5]+"****" %></td>        <td width="130"> <%= ii.MobileNo[0..-5]+"****" %></td>
            </tr>
            <tr>
              <td width="13">&nbsp;</td>        <td width="207"> <%= ii.OwnerName[0..1]+"*" %></td>        <td colspan="2">&nbsp;</td>      </tr>
            <tr>
              <td>&nbsp;</td>        <td> <%= ii.Address[0..-5]+"****" %></td>        <td>&nbsp;</td>        <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>        <td>&nbsp;</td>        <td>&nbsp;</td>        <td>&nbsp;</td>
            </tr>
            <tr>
              <td width="13">&nbsp;</td>
              <td colspan="3">한신약* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;서울 동대문구 용**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;02-924-****</td>
            </tr>
          </table>

  <table width="500" height="230" class="font1">
    <tr>
      <td>&nbsp;</td>
      <td height="44" valign="bottom">&nbsp;</td>
      <td>&nbsp;</td>
      <td valign="bottom">&nbsp;</td>
    </tr>
    <tr>
      <td width="13">&nbsp;</td>
      <td width="170" height="60" class="font1">취급주의(급송요망)<br />
        의약품</p></td>
      <td width="180">&nbsp;</td>
      <td width="110" class="font1">서울권
        <br>2015-1-26<br/></td>
    </tr>

    <tr>
      <td height="127">&nbsp;</td>
      <td><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P0101014507150004<br /><br />
        <span class="font2">연수구</span></p></td>
      <td colspan="2" align="right"><div class="barcode39" style="width:270px;height:70px;">
        1745695254
      </div></td>
    </tr>


  </table>
  <table width="500" class="font1">
    <tr>
      <td width="13" height="20">&nbsp;</td>
      <td width="170" ><%= ii.PrdName[0..-2]+"**" %></td>
      <td width="157" ><%= ii.PhoneNo[0..-5]+"****" %></td>
      <td width="130" ><%= ii.MobileNo[0..-5]+"****" %></td>
    </tr>
    <tr>
      <td width="13" height="20">&nbsp;</td>
      <td width="203"><%= ii.OwnerName[0..1]+"*" %></td>
      <td colspan="2" >&nbsp;</td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
      <td width="250"><%= ii.Address[0..-5]+"****" %></td>
      <td >&nbsp;</td>
    </tr>
    <tr>
      <td height="60">&nbsp;</td>
      <td colspan="3"><span>한신약* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;서울 동대문구 용**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;02-924-****</span></td>
    </tr>
    <tr>
      <td width="13" height="23">&nbsp;</td>
      <td colspan="3" class="font4">&nbsp;</td>
    </tr>
  </table>

            <table width="500" class="header">
              <tr>
                <td>&nbsp;</td>        <td>&nbsp;</td>        <td><%= ii.NumEY %></td>        <td><div class="barcode39" style="width:150px;height:40px;">
                1745695254
              </div></td>
              </tr>
              <tr>
                <td width="13">&nbsp;</td>        <td width="220">  <%= ii.PrdName[0..-2]+"**" %></td>        <td width="123"> <%= ii.PhoneNo[0..-5]+"****" %></td>        <td width="123"> <%= ii.MobileNo[0..-5]+"****" %></td>
              </tr>
              <tr>
                <td width="13">&nbsp;</td>        <td width="220"> <%= ii.OwnerName[0..1]+"*" %></td>        <td colspan="2">&nbsp;</td>      </tr>
              <tr>
                <td>&nbsp;</td>        <td width="220"> <%= ii.Address[0..-5]+"****" %></td>        <td width="123">&nbsp;</td>        <td width="123">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>        <td>&nbsp;</td>        <td>&nbsp;</td>        <td>&nbsp;</td>
              </tr>
              <tr>
                <td width="13">&nbsp;</td>
                <td colspan="3">한신약* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;서울 동대문구 용**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;02-924-****</td>
              </tr>
            </table>



</div>
    <% end %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datesent:</strong> <%= @invoice.DateSent %>
</p>

<p>
  <strong>Datepage:</strong> <%= @invoice.DatePage %>
</p>

<p>
  <strong>Numey:</strong> <%= @invoice.NumEY %>
</p>

<p>
  <strong>Orderno:</strong> <%= @invoice.OrderNo %>
</p>

<p>
  <strong>Acccode:</strong> <%= @invoice.AccCode %>
</p>

<p>
  <strong>Prdname:</strong> <%= @invoice.PrdName %>
</p>

<p>
  <strong>Ownername:</strong> <%= @invoice.OwnerName %>
</p>

<p>
  <strong>Phoneno:</strong> <%= @invoice.PhoneNo %>
</p>

<p>
  <strong>Mobileno:</strong> <%= @invoice.MobileNo %>
</p>

<p>
  <strong>Zipcode:</strong> <%= @invoice.ZipCode %>
</p>

<p>
  <strong>Address:</strong> <%= @invoice.Address %>
</p>

<p>
  <strong>Iweight:</strong> <%= @invoice.iWeight %>
</p>

<p>
  <strong>Name1:</strong> <%= @invoice.Name1 %>
</p>

<p>
  <strong>Cnt1:</strong> <%= @invoice.Cnt1 %>
</p>

<p>
  <strong>Iprice:</strong> <%= @invoice.iPrice %>
</p>

<p>
  <strong>Memo:</strong> <%= @invoice.Memo %>
</p>

<p>
  <strong>Ipage:</strong> <%= @invoice.iPage %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Go5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PrdName %><br>
    <%= f.text_field :PrdName %>
  </div>
  <div class="field">
    <%= f.label :OwnerName %><br>
    <%= f.text_field :OwnerName %>
  </div>
  <div class="field">
    <%= f.label :PhoneNo %><br>
    <%= f.text_field :PhoneNo %>
  </div>
  <div class="field">
    <%= f.label :MobileNo %><br>
    <%= f.text_field :MobileNo %>
  </div>
  <div class="field">
    <%= f.label :ZipCode %><br>
    <%= f.text_field :ZipCode %>
  </div>
  <div class="field">
    <%= f.label :Address %><br>
    <%= f.text_field :Address %>
  </div>
  <div class="field">
    <%= f.label :iWeight %><br>
    <%= f.number_field :iWeight %>
  </div>
  <div class="field">
    <%= f.label :Name1 %><br>
    <%= f.text_field :Name1 %>
  </div>
  <div class="field">
    <%= f.label :Cnt1 %><br>
    <%= f.text_field :Cnt1 %>
  </div>
  <div class="field">
    <%= f.label :iPrice %><br>
    <%= f.number_field :iPrice %>
  </div>
  <div class="field">
    <%= f.label :Memo %><br>
    <%= f.text_field :Memo %>
  </div>
  <div class="field">
    <%= f.label :iPage %><br>
    <%= f.number_field :iPage %>
  </div>
  <div class="field">
    <%= f.label :OrderNo %><br>
    <%= f.text_field :OrderNo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Prdname</th>
      <th>Ownername</th>
      <th>Phoneno</th>
      <th>Mobileno</th>
      <th>Zipcode</th>
      <th>Address</th>
      <th>Iweight</th>
      <th>Name1</th>
      <th>Cnt1</th>
      <th>Iprice</th>
      <th>Memo</th>
      <th>Ipage</th>
      <th>Orderno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.PrdName %></td>
        <td><%= product.OwnerName %></td>
        <td><%= product.PhoneNo %></td>
        <td><%= product.MobileNo %></td>
        <td><%= product.ZipCode %></td>
        <td><%= product.Address %></td>
        <td><%= product.iWeight %></td>
        <td><%= product.Name1 %></td>
        <td><%= product.Cnt1 %></td>
        <td><%= product.iPrice %></td>
        <td><%= product.Memo %></td>
        <td><%= product.iPage %></td>
        <td><%= product.OrderNo %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prdname:</strong>
  <%= @product.PrdName %>
</p>

<p>
  <strong>Ownername:</strong>
  <%= @product.OwnerName %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @product.PhoneNo %>
</p>

<p>
  <strong>Mobileno:</strong>
  <%= @product.MobileNo %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @product.ZipCode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @product.Address %>
</p>

<p>
  <strong>Iweight:</strong>
  <%= @product.iWeight %>
</p>

<p>
  <strong>Name1:</strong>
  <%= @product.Name1 %>
</p>

<p>
  <strong>Cnt1:</strong>
  <%= @product.Cnt1 %>
</p>

<p>
  <strong>Iprice:</strong>
  <%= @product.iPrice %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @product.Memo %>
</p>

<p>
  <strong>Ipage:</strong>
  <%= @product.iPage %>
</p>

<p>
  <strong>Orderno:</strong>
  <%= @product.OrderNo %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>